# Generated by Django 4.0.1 on 2022-04-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_model_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question3',
            new_name='Question4',
        ),
    ]
